# Generated by Django 4.2.30 on 2026-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='cover_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
