# Generated by Django 4.2.30 on 2026-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_gameentry_cover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
